# Generated by Django 3.0.7 on 2020-06-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Project_Blog',
        ),
    ]
